language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel

r_check_args
  - --run-donttest
  - --run-dontrun
  - --timings

before_install:
  - Rscript -e "update.packages(ask = FALSE)"
  - Rscript -e "install.packages('covr')"

after_success:
  - Rscript -e "covr::codecov()"

before_deploy:
  - Rscript -e "dimRed::installSuggests()"
  - Rscript -e "devtools::document()"
